CREATE DOMAIN UINT AS INT CHECK (VALUE >= 0);
CREATE DOMAIN USMALLINT AS SMALLINT CHECK (VALUE >= 0);

CREATE DOMAIN POSITIVE_INT AS INT CHECK (VALUE > 0);
CREATE DOMAIN POSITIVE_NUMBER AS NUMERIC CHECK (VALUE > 0);
CREATE DOMAIN POSITIVE_SMALLINT AS SMALLINT CHECK (VALUE > 0);

CREATE DOMAIN DISCORD_ID AS BIGINT;
CREATE DOMAIN PERCENTAGE AS NUMERIC CHECK(VALUE >= 0 AND VALUE <= 100);

CREATE DOMAIN FONT AS VARCHAR(64);
CREATE DOMAIN URL AS VARCHAR(512) CHECK(VALUE LIKE 'http%');
CREATE DOMAIN COLOR AS INT CHECK(VALUE >= 0 AND VALUE <= 16777215);

CREATE TYPE LOCALE AS ENUM ('RU', 'EN');
CREATE TYPE DISCORD_ROLE_ACTION AS ENUM ('ADD', 'REMOVE', 'TOGGLE');
CREATE TYPE DISCORD_BUTTON_STYLE AS ENUM ('PRIMARY', 'SECONDARY', 'DANGER', 'SUCCESS');